---
title: 'Hub, Toeplitz and Banded precision matrices : inverse correlation'
author: "Kushal K Dey"
date: "3/8/2018"
output: html_document
---

## Hub correlation

```{r}
library(gridExtra)
library(ggplot2)
library(scales)
cols <- c("#F8766D", "#CD9600", "#7CAE00", "#00BE67", "#00BFC4", "#00A9FF", "#C77CFF", "#FF61CC")
```

```{r}
hub_n_10_P_100 <- get(load("../output/Icor/hub_cmd_boot_n_10_P_100_results_icor.rda"))
hub_n_50_P_100 <- get(load("../output/Icor/hub_cmd_boot_n_50_P_100_results_icor.rda"))
hub_n_100_P_100 <- get(load("../output/Icor/hub_cmd_boot_n_100_P_100_results_icor.rda"))
hub_n_1000_P_100 <- get(load("../output/Icor/hub_cmd_boot_n_1000_P_100_results_icor.rda"))

df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(hub_n_10_P_100[,1], hub_n_10_P_100[,2],
                                    hub_n_10_P_100[,3], hub_n_10_P_100[,4],
                                    hub_n_10_P_100[,5], hub_n_10_P_100[,6],
                                    hub_n_10_P_100[,7])))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p1 <- p + geom_boxplot() + theme_bw() + theme(legend.position="none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + ggtitle(paste0("n = ", 10, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))


df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(hub_n_50_P_100[,1], hub_n_50_P_100[,2],
                                    hub_n_50_P_100[,3], hub_n_50_P_100[,4],
                                    hub_n_50_P_100[,5], hub_n_50_P_100[,6],
                                    hub_n_50_P_100[,7])))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p2 <- p + geom_boxplot() + theme_bw() + theme(legend.position="none") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  ggtitle(paste0("n = ", 50, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))


df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(hub_n_100_P_100[,1], hub_n_100_P_100[,2],
                                    hub_n_100_P_100[,3], hub_n_100_P_100[,4],
                                    hub_n_100_P_100[,5], hub_n_100_P_100[,6],
                                    hub_n_100_P_100[,7]
                                    )))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p3 <- p + geom_boxplot() + theme_bw() + theme(legend.position="none") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  ggtitle(paste0("n = ", 100, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))


method1 <- factor(c(rep("empirical", 0),rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("empirical", "corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1"))
df <- data.frame("method" = method1[, drop=FALSE],
                 "distance" = log(c(hub_n_1000_P_100[,1], hub_n_1000_P_100[,2],
                                    hub_n_1000_P_100[,3], hub_n_1000_P_100[,4],
                                    hub_n_1000_P_100[,5], hub_n_1000_P_100[,6],
                                    hub_n_1000_P_100[,7]
                                    )))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p4 <- p + geom_boxplot()+ theme_bw() + theme(legend.position="none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + ggtitle(paste0("n = ", 1000, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))
p4
grid.arrange(p1, p2, p3, p4, nrow = 2, ncol = 2) 
 

```

## Toeplitz matrix

```{r}
toeplitz_n_10_P_100 <- get(load("../output/Icor/toeplitz_cmd_n_10_P_100_results_icor.rda"))
toeplitz_n_50_P_100 <- get(load("../output/Icor/toeplitz_cmd_n_50_P_100_results_icor.rda"))
toeplitz_n_100_P_100 <- get(load("../output/Icor/toeplitz_cmd_n_100_P_100_results_icor.rda"))
toeplitz_n_1000_P_100 <- get(load("../output/Icor/toeplitz_cmd_n_1000_P_100_results_icor.rda"))

df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(toeplitz_n_10_P_100[,1], toeplitz_n_10_P_100[,2],
                                    toeplitz_n_10_P_100[,3], toeplitz_n_10_P_100[,4],
                                    toeplitz_n_10_P_100[,5], toeplitz_n_10_P_100[,6],
                                    toeplitz_n_10_P_100[,7])))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p5 <- p + geom_boxplot() + theme_bw() + theme(legend.position="none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + ggtitle(paste0("n = ", 10, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))


df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(toeplitz_n_50_P_100[,1], toeplitz_n_50_P_100[,2],
                                    toeplitz_n_50_P_100[,3], toeplitz_n_50_P_100[,4],
                                    toeplitz_n_50_P_100[,5], toeplitz_n_50_P_100[,6],
                                    toeplitz_n_50_P_100[,7])))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p6 <- p + geom_boxplot() + theme_bw() + theme(legend.position="none") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  ggtitle(paste0("n = ", 50, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))



df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(toeplitz_n_100_P_100[,1], toeplitz_n_100_P_100[,2],
                                    toeplitz_n_100_P_100[,3], toeplitz_n_100_P_100[,4],
                                    toeplitz_n_100_P_100[,5], toeplitz_n_100_P_100[,6],
                                    toeplitz_n_100_P_100[,7]
                                    )))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p7 <- p + geom_boxplot() + theme_bw() + theme(legend.position="none") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  ggtitle(paste0("n = ", 100, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))


df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(toeplitz_n_1000_P_100[,1], toeplitz_n_1000_P_100[,2],
                                    toeplitz_n_1000_P_100[,3], toeplitz_n_1000_P_100[,4],
                                    toeplitz_n_1000_P_100[,5], toeplitz_n_1000_P_100[,6],
                                    toeplitz_n_1000_P_100[,7]
                                    )))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p8 <- p + geom_boxplot()+ theme_bw() + theme(legend.position="none") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + ggtitle(paste0("n = ", 1000, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))


grid.arrange(p5, p6, p7, p8, nrow = 2, ncol = 2) 
```


## Banded precision matrix

```{r}
banded_precision_n_10_P_100 <- get(load("../output/Icor/banded_precision_n_10_P_100_results_icor.rda"))
banded_precision_n_50_P_100 <- get(load("../output/Icor/banded_precision_n_50_P_100_results_icor.rda"))
banded_precision_n_100_P_100 <- get(load("../output/Icor/banded_precision_n_100_P_100_results_icor.rda"))
banded_precision_n_1000_P_100 <- get(load("../output/Icor/banded_precision_n_1000_P_100_results_icor.rda"))

df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(banded_precision_n_10_P_100[,1], banded_precision_n_10_P_100[,2],
                                    banded_precision_n_10_P_100[,3], banded_precision_n_10_P_100[,4],
                                    banded_precision_n_10_P_100[,5], banded_precision_n_10_P_100[,6],
                                    banded_precision_n_10_P_100[,7])))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p9 <- p + geom_boxplot() + theme_bw() + theme(legend.position="none") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + ggtitle(paste0("n = ", 10, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))


df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(banded_precision_n_50_P_100[,1], banded_precision_n_50_P_100[,2],
                                    banded_precision_n_50_P_100[,3], banded_precision_n_50_P_100[,4],
                                    banded_precision_n_50_P_100[,5], banded_precision_n_50_P_100[,6],
                                    banded_precision_n_50_P_100[,7])))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p10 <- p + geom_boxplot() + theme_bw() + theme(legend.position="none") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  ggtitle(paste0("n = ", 50, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))



df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(banded_precision_n_100_P_100[,1], banded_precision_n_100_P_100[,2],
                                    banded_precision_n_100_P_100[,3], banded_precision_n_100_P_100[,4],
                                    banded_precision_n_100_P_100[,5], banded_precision_n_100_P_100[,6],
                                    banded_precision_n_100_P_100[,7]
                                    )))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p11 <- p + geom_boxplot() + theme_bw() + theme(legend.position="none") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  ggtitle(paste0("n = ", 100, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))


df <- data.frame("method" = factor(c(rep("corpcor", 50), rep("corshrink", 50),
                              rep("pdsce",50), rep("glasso:1e-02", 50),
                              rep("glasso:0.1", 50), rep("glasso:0.5", 50), rep("glasso:1", 50)), 
                              levels = c("corpcor",
                                        "corshrink", "pdsce",
                                        "glasso:1e-02",
                                        "glasso:0.1",
                                        "glasso:0.5",
                                        "glasso:1")),
                 "distance" = log(c(banded_precision_n_1000_P_100[,1], banded_precision_n_1000_P_100[,2],
                                    banded_precision_n_1000_P_100[,3], banded_precision_n_1000_P_100[,4],
                                    banded_precision_n_1000_P_100[,5], banded_precision_n_1000_P_100[,6],
                                    banded_precision_n_1000_P_100[,7]
                                    )))

p <- ggplot(df, aes(method, distance, color = method)) + ylab("log(distance)")
p12 <- p + geom_boxplot()+ theme_bw() + theme(legend.position="none") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + ggtitle(paste0("n = ", 1000, " p = ", 100)) +
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))


grid.arrange(p9, p10, p11, p12, nrow = 2, ncol = 2) 
```

```{r}
p <- ggplot(df, aes(method, distance, color = method)) + xlab("") + ylab("log(distance)")+ ggtitle("n=1000, p = 100")
p13 <- p + geom_boxplot() + theme_bw() + 
scale_y_continuous(breaks= pretty_breaks()) + scale_colour_manual(values = c("empirical" = cols[1], "corpcor" = cols[2], "corshrink" = cols[3], "pdsce" = cols[4], "glasso:1e-02" = cols[5],
"glasso:0.1" = cols[6], "glasso:0.5" = cols[7], "glasso:1" = cols[8]))

print(p13)
```


```{r fig.width = 10, fig.height = 8}
grid.arrange(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12, nrow = 4, ncol = 3, as.table = FALSE) 
```
  
