---
title: "Corshrink on hub correlation matrices"
author: "Kushal K Dey"
date: "1/2/2018"
output: html_document
---

```{r setup, include=FALSE}
library(CorShrink)
library(huge)
library(corpcor)
```

## n= 10, P = 200

```{r}
n <- 10
P <- 200
block <- 20
mat <- 0.3*diag(1,block) + 0.7*rep(1,block) %*% t(rep(1, block))
Sigma <-   bdiag(mat, mat, mat, mat, mat, mat, mat, mat, mat, mat)
```

```{r}
col=c(rep(rgb(0,1,0), 10000),rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)), rep(rgb(1,0,0),10000))

image(as.matrix(cov2cor(Sigma)),
      col=col, main=paste0("pop corr matrix"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))
```

```{r}
set.seed(100)
data <- mvrnorm(n,rep(0,P),Sigma)
corSigma <- cov2cor(Sigma)
```

```{r echo=TRUE, eval= FALSE}
out.npn = huge(data, lambda = c(seq(1e-10, 0.1, length.out = 100), 
                                seq(0.1, 100, length.out = 100)), method = "glasso", cov.output = TRUE)
save(out.npn, file = "../output/huge_hub_n_10_P_100.rda")
```

```{r}

## GLASSO

out.npn = get(load(file = "../output/huge_hub_n_10_P_100.rda"))
out.select.npn = huge.select(out.npn)
est_cov <- out.select.npn$opt.cov
est_icov <- out.select.npn$opt.icov
out.select.npn$opt.lambda

# est_icov <- out.npn$icov[[which.max(out.npn$loglik)]]
# est_cov <- out.npn$cov[[which.max(out.npn$loglik)]]
# 
# est_icov <- out.npn$icov[[80]]
# est_cov <- out.npn$cov[[80]]
# 
# ## Shafer Strimmer 

strimmer_sample <- corpcor::cor.shrink(data)

## CorShrink

cov_sample_ML <-  CorShrinkData(data, sd_boot = FALSE, optmethod = "mixEM",
                     image.control = list(x.cex = 0.3, y.cex = 0.3),
                     ash.control = list())

```

All methods - covariance matrix 

```{r}

col=c(rep(rgb(0,1,0), 10000),rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)), rep(rgb(1,0,0),10000))

par(mfrow = c(2,2))

image(as.matrix(cor(out.npn$data)),
      col=col, main=paste0("sample corr matrix"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(cov2cor(as.matrix(est_cov)),
      col=col, main=paste0("GLASSO"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(strimmer_sample,
      col=col, main=paste0("shafer strimmer"), cex.main=2,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(as.matrix(cov_sample_ML$ash_cor_PD),
      col=col, main=paste0("CorShrink"), cex.main=2,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

```

## n= 50, P = 200

```{r}
n <- 50
P <- 200
block <- 20
mat <- 0.3*diag(1,block) + 0.7*rep(1,block) %*% t(rep(1, block))
Sigma <-   bdiag(mat, mat, mat, mat, mat, mat, mat, mat, mat, mat)
```

```{r}
col=c(rep(rgb(0,1,0), 10000),rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)), rep(rgb(1,0,0),10000))

image(as.matrix(cov2cor(Sigma)),
      col=col, main=paste0("pop corr matrix"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))
```

```{r}
set.seed(100)
data <- mvrnorm(n,rep(0,P),Sigma)
corSigma <- cov2cor(Sigma)
```

```{r echo=TRUE, eval= FALSE}
out.npn = huge(data, lambda = c(seq(1e-05, 0.1, length.out = 100), 
                                seq(0.1, 100, length.out = 100)), method = "glasso", cov.output = TRUE)
save(out.npn, file = "../output/huge_hub_n_50_P_200.rda")
```

```{r}

## GLASSO

out.npn = get(load(file = "../output/huge_hub_n_50_P_200.rda"))
out.select.npn = huge.select(out.npn)
est_cov <- out.select.npn$opt.cov
est_icov <- out.select.npn$opt.icov
out.select.npn$opt.lambda

# est_icov <- out.npn$icov[[which.max(out.npn$loglik)]]
# est_cov <- out.npn$cov[[which.max(out.npn$loglik)]]
# 
# est_icov <- out.npn$icov[[80]]
# est_cov <- out.npn$cov[[80]]
# 
# ## Shafer Strimmer 

strimmer_sample <- corpcor::cor.shrink(data)

## CorShrink

cov_sample_ML <-  CorShrinkData(data, sd_boot = FALSE, optmethod = "mixEM",
                     image.control = list(x.cex = 0.3, y.cex = 0.3),
                     ash.control = list())

```


All methods - covariance matrix 

```{r}

col=c(rep(rgb(0,1,0), 1),rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)), rep(rgb(1,0,0),1))

par(mfrow = c(2,2))

image(as.matrix(cor(out.npn$data)),
      col=col, main=paste0("sample corr matrix"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(cov2cor(as.matrix(est_cov)),
      col=col, main=paste0("GLASSO"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(strimmer_sample,
      col=col, main=paste0("shafer strimmer"), cex.main=2,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(as.matrix(cov_sample_ML$ash_cor_PD),
      col=col, main=paste0("CorShrink"), cex.main=2,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

```

## n= 100, P = 200

```{r}
n <- 100
P <- 200
block <- 20
mat <- 0.3*diag(1,block) + 0.7*rep(1,block) %*% t(rep(1, block))
Sigma <-   bdiag(mat, mat, mat, mat, mat, mat, mat, mat, mat, mat)
```

```{r}
col=c(rep(rgb(0,1,0), 10000),rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)), rep(rgb(1,0,0),10000))

image(as.matrix(cov2cor(Sigma)),
      col=col, main=paste0("pop corr matrix"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))
```

```{r}
set.seed(101)
data <- mvrnorm(n,rep(0,P),Sigma)
corSigma <- cov2cor(Sigma)
```

```{r echo=TRUE, eval= FALSE}
out.npn = huge(data, lambda = c(seq(1e-05, 0.1, length.out = 100), 
                                seq(0.1, 100, length.out = 100)), method = "glasso", cov.output = TRUE)
save(out.npn, file = "../output/huge_hub_n_100_P_200.rda")
```

```{r}

## GLASSO

out.npn = get(load(file = "../output/huge_hub_n_100_P_200.rda"))
out.select.npn = huge.select(out.npn)
est_cov <- out.select.npn$opt.cov
est_icov <- out.select.npn$opt.icov
out.select.npn$opt.lambda

# est_icov <- out.npn$icov[[which.max(out.npn$loglik)]]
# est_cov <- out.npn$cov[[which.max(out.npn$loglik)]]
# 
# est_icov <- out.npn$icov[[80]]
# est_cov <- out.npn$cov[[80]]
# 
# ## Shafer Strimmer 

strimmer_sample <- corpcor::cor.shrink(data)

## CorShrink

cov_sample_ML <-  CorShrinkData(data, sd_boot = FALSE, optmethod = "mixEM",
                     image.control = list(x.cex = 0.3, y.cex = 0.3),
                     ash.control = list())

```



All methods - covariance matrix 

```{r}

col=c(rep(rgb(0,1,0), 10000),rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)), rep(rgb(1,0,0),10000))

par(mfrow = c(2,2))

image(as.matrix(cor(out.npn$data)),
      col=col, main=paste0("sample corr matrix"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(cov2cor(as.matrix(est_cov)),
      col=col, main=paste0("GLASSO"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(strimmer_sample,
      col=col, main=paste0("shafer strimmer"), cex.main=2,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(as.matrix(cov_sample_ML$ash_cor_PD),
      col=col, main=paste0("CorShrink"), cex.main=2,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

```

## n= 200, P = 200

```{r}
n <- 200
P <- 200
block <- 20
mat <- 0.3*diag(1,block) + 0.7*rep(1,block) %*% t(rep(1, block))
Sigma <-   bdiag(mat, mat, mat, mat, mat, mat, mat, mat, mat, mat)
```

```{r}
col=c(rep(rgb(0,1,0), 10000),rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)), rep(rgb(1,0,0),10000))

image(as.matrix(cov2cor(Sigma)),
      col=col, main=paste0("pop corr matrix"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))
```

```{r}
set.seed(100)
data <- mvrnorm(n,rep(0,P),Sigma)
corSigma <- cov2cor(Sigma)
```

```{r echo=TRUE, eval= FALSE}
out.npn = huge(data, lambda = c(seq(1e-05, 0.1, length.out = 100), 
                                seq(0.1, 100, length.out = 100)), method = "glasso", cov.output = TRUE)
save(out.npn, file = "../output/huge_hub_n_200_P_200.rda")
```

```{r}

## GLASSO

out.npn = get(load(file = "../output/huge_hub_n_200_P_200.rda"))
out.select.npn = huge.select(out.npn)
est_cov <- out.select.npn$opt.cov
est_icov <- out.select.npn$opt.icov
out.select.npn$opt.lambda

# est_icov <- out.npn$icov[[which.max(out.npn$loglik)]]
# est_cov <- out.npn$cov[[which.max(out.npn$loglik)]]
# 
# est_icov <- out.npn$icov[[80]]
# est_cov <- out.npn$cov[[80]]
# 
# ## Shafer Strimmer 

strimmer_sample <- corpcor::cor.shrink(data)

## CorShrink

cov_sample_ML <-  CorShrinkData(data, sd_boot = FALSE, optmethod = "mixEM",
                     image.control = list(x.cex = 0.3, y.cex = 0.3),
                     ash.control = list())

```



All methods - covariance matrix 

```{r}

col=c(rep(rgb(0,1,0), 10000),rev(rgb(seq(1,0,length=1000),1,seq(1,0,length=1000))),
      rgb(1,seq(1,0,length=1000),seq(1,0,length=1000)), rep(rgb(1,0,0),10000))

par(mfrow = c(2,2))

image(as.matrix(cor(out.npn$data)),
      col=col, main=paste0("sample corr matrix"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(cov2cor(as.matrix(est_cov)),
      col=col, main=paste0("GLASSO"), cex.main=1,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(strimmer_sample,
      col=col, main=paste0("shafer strimmer"), cex.main=2,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

image(as.matrix(cov_sample_ML$ash_cor_PD),
      col=col, main=paste0("CorShrink"), cex.main=2,
      xaxt = "n", yaxt = "n", zlim=c(-1,1))

```
